export const TOGGLE_THEME = 'TOGGLE_THEME'

export const TURN_ON_TAB = 'TURN_ON_TAB'
export const TURN_OFF_TAB = 'TURN_OFF_TAB'

export const TURN_ON_ALERT = 'TURN_ON_ALERT'
export const TURN_DOWN_ALERT = 'TURN_DOWN_ALERT'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_GET_PROFILE = 'USER_GET_PROFILE'
export const USER_GET_IMAGE = 'USER_GET_IMAGE'

export const ROUTING_ON = 'ROUTING_ON'
export const ROUTING_OFF = 'ROUTING_OFF'

export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION'

export const LOADING_ON = 'LOADING_ON'
export const LOADING_OFF = 'LOADING_OFF'

export const CHAPEL_GET = 'CHAPEL_GET'
export const SORING_CHAPEL = 'SORING_CHAPEL'
export const CHAPEL_UPDATE_CURRENT = 'CHAPEL_UPDATE_CURRENT'

export const MOBILE_STUDENT_CARD_ON = 'MOBILE_STUDENT_CARD_ON'
export const MOBILE_STUDENT_CARD_OFF = 'MOBILE_STUDENT_CARD_OFF'

export const MILEAGE_GET_BALANCE = 'MILEAGE_GET_BALANCE'

export const TIME_TABLE_FETCH = 'TIME_TABLE_FETCH'

export const SET_COLOR_SET = 'SET_COLOR_SET'

export const FETCH_LECTURE_CODE = 'FETCH_LECTURE_CODE'

export const ATTENDANCE_ON = 'ATTENDANCE_ON'
export const ATTENDANCE_OFF = 'ATTENDANCE_OFF'
export const FETCH_ATTENDANCE = 'FETCH_ATTENDANCE'
export const SORT_ATTENDANCES = 'SORT_ATTENDANCES'
export const ATTENDANCE_DETAIL_LIST_TABLE_ON = 'ATTENDANCE_DETAIK_LIST_TABLE_ON'
export const ATTENDANCE_DETAIL_LIST_TABLE_OFF = 'ATTENDANCE_DETAIK_LIST_TABLE_OFF'
export const CLICK_SPECIFIC_ATTENDANCE_INFO = 'CLICK_SPECIFIC_ATTENDANCE_INFO'

export const FETCH_LECTURES = 'FETCH_LECTURES'
export const SELECT_LECTURE = 'SELECT_LECTURE'


export const FETCH_KBU_SCHEDULE = 'FETCH_KBU_SCHEDULE'
export const FETCH_OFFDAYS_SCHEDULE = 'FETCH_OFFDAYS_SCHEDULE'


export const SCHEDULE_DETAIL_ON = 'SCHEDULE_ON'
export const SCHEDULE_DETAIL_OFF = 'SCHEDULE_OFF'

export const FETCH_MCU = 'FETCH_MCU'
export const MCU_LOADING = 'MCU_LOADING'
export const MCU_OFF = 'MCU_OFF'